nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: This is an awesome app! Hell Yeah!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/user
            - ^/api(?!/docs$)(?!/docs.json$) # Accepts routes under /api except /api/doc
